title: "Software Development Consultant | Winter Softworks"
h1: "Steve Nield"
personal-description: "Full Stack Developer and Architect"
status: "Currently consulting with a number of start-up projects, helping to move them from prototype to market."

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
