title: "Software Development Consultant | Winter Softworks"
h1: "Steve Nield"
personal-description: "Full Stack Developer and Architect"
status: "Currently consulting with a number of start-up projects, helping to move them from prototype to market."
permalink: "/:title"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
